// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Series struct {
	ID            pgtype.UUID      `json:"id"`
	KinopoiskID   int32            `json:"kinopoisk_id"`
	Title         string           `json:"title"`
	OriginalTitle pgtype.Text      `json:"original_title"`
	PosterUrl     pgtype.Text      `json:"poster_url"`
	Year          pgtype.Int4      `json:"year"`
	Description   pgtype.Text      `json:"description"`
	TotalEpisodes pgtype.Int4      `json:"total_episodes"`
	TotalSeasons  pgtype.Int4      `json:"total_seasons"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserProgress struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	SeriesID       pgtype.UUID      `json:"series_id"`
	CurrentSeason  int32            `json:"current_season"`
	CurrentEpisode int32            `json:"current_episode"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
