// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: series.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (kinopoisk_id, title, original_title, poster_url, year, description, total_episodes, total_seasons, is_serial)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, kinopoisk_id, title, original_title, poster_url, year, description, total_episodes, total_seasons, is_serial, created_at, updated_at
`

type CreateSeriesParams struct {
	KinopoiskID   int32       `json:"kinopoisk_id"`
	Title         string      `json:"title"`
	OriginalTitle pgtype.Text `json:"original_title"`
	PosterUrl     pgtype.Text `json:"poster_url"`
	Year          pgtype.Int4 `json:"year"`
	Description   pgtype.Text `json:"description"`
	TotalEpisodes pgtype.Int4 `json:"total_episodes"`
	TotalSeasons  pgtype.Int4 `json:"total_seasons"`
	IsSerial      bool        `json:"is_serial"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.KinopoiskID,
		arg.Title,
		arg.OriginalTitle,
		arg.PosterUrl,
		arg.Year,
		arg.Description,
		arg.TotalEpisodes,
		arg.TotalSeasons,
		arg.IsSerial,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.KinopoiskID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterUrl,
		&i.Year,
		&i.Description,
		&i.TotalEpisodes,
		&i.TotalSeasons,
		&i.IsSerial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeriesByID = `-- name: GetSeriesByID :one
SELECT id, kinopoisk_id, title, original_title, poster_url, year, description, total_episodes, total_seasons, created_at, updated_at
FROM series
WHERE id = $1
`

func (q *Queries) GetSeriesByID(ctx context.Context, id pgtype.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesByID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.KinopoiskID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterUrl,
		&i.Year,
		&i.Description,
		&i.TotalEpisodes,
		&i.TotalSeasons,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeriesByKinopoiskID = `-- name: GetSeriesByKinopoiskID :one
SELECT id, kinopoisk_id, title, original_title, poster_url, year, description, total_episodes, total_seasons, created_at, updated_at
FROM series
WHERE kinopoisk_id = $1
`

func (q *Queries) GetSeriesByKinopoiskID(ctx context.Context, kinopoiskID int32) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesByKinopoiskID, kinopoiskID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.KinopoiskID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterUrl,
		&i.Year,
		&i.Description,
		&i.TotalEpisodes,
		&i.TotalSeasons,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, kinopoisk_id, title, original_title, poster_url, year, description, total_episodes, total_seasons, created_at, updated_at
FROM series
WHERE title ILIKE '%' || $1 || '%'
ORDER BY title
LIMIT $2
`

type SearchSeriesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, searchSeries, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.KinopoiskID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterUrl,
			&i.Year,
			&i.Description,
			&i.TotalEpisodes,
			&i.TotalSeasons,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
