// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_progress.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProgress = `-- name: CreateUserProgress :one
INSERT INTO user_progress (user_id, series_id, current_season, current_episode, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, series_id, current_season, current_episode, status, created_at, updated_at
`

type CreateUserProgressParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	SeriesID       pgtype.UUID `json:"series_id"`
	CurrentSeason  int32       `json:"current_season"`
	CurrentEpisode int32       `json:"current_episode"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateUserProgress(ctx context.Context, arg CreateUserProgressParams) (UserProgress, error) {
	row := q.db.QueryRow(ctx, createUserProgress,
		arg.UserID,
		arg.SeriesID,
		arg.CurrentSeason,
		arg.CurrentEpisode,
		arg.Status,
	)
	var i UserProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesID,
		&i.CurrentSeason,
		&i.CurrentEpisode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserProgress = `-- name: DeleteUserProgress :exec
DELETE FROM user_progress
WHERE user_id = $1 AND series_id = $2
`

type DeleteUserProgressParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	SeriesID pgtype.UUID `json:"series_id"`
}

func (q *Queries) DeleteUserProgress(ctx context.Context, arg DeleteUserProgressParams) error {
	_, err := q.db.Exec(ctx, deleteUserProgress, arg.UserID, arg.SeriesID)
	return err
}

const getAllUserProgress = `-- name: GetAllUserProgress :many
SELECT up.id, up.user_id, up.series_id, up.current_season, up.current_episode, up.status, up.created_at, up.updated_at,
       s.id as s_id, s.kinopoisk_id, s.title, s.original_title, s.poster_url, s.year, s.description, s.total_episodes, s.total_seasons, s.is_serial
FROM user_progress up
JOIN series s ON up.series_id = s.id
WHERE up.user_id = $1
ORDER BY up.updated_at DESC
`

type GetAllUserProgressRow struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	SeriesID       pgtype.UUID      `json:"series_id"`
	CurrentSeason  int32            `json:"current_season"`
	CurrentEpisode int32            `json:"current_episode"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	SID            pgtype.UUID      `json:"s_id"`
	KinopoiskID    int32            `json:"kinopoisk_id"`
	Title          string           `json:"title"`
	OriginalTitle  pgtype.Text      `json:"original_title"`
	PosterUrl      pgtype.Text      `json:"poster_url"`
	Year           pgtype.Int4      `json:"year"`
	Description    pgtype.Text      `json:"description"`
	TotalEpisodes  pgtype.Int4      `json:"total_episodes"`
	TotalSeasons   pgtype.Int4      `json:"total_seasons"`
	IsSerial       pgtype.Bool      `json:"is_serial"`
}

func (q *Queries) GetAllUserProgress(ctx context.Context, userID pgtype.UUID) ([]GetAllUserProgressRow, error) {
	rows, err := q.db.Query(ctx, getAllUserProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserProgressRow{}
	for rows.Next() {
		var i GetAllUserProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeriesID,
			&i.CurrentSeason,
			&i.CurrentEpisode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.KinopoiskID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterUrl,
			&i.Year,
			&i.Description,
			&i.TotalEpisodes,
			&i.TotalSeasons,
			&i.IsSerial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProgress = `-- name: GetUserProgress :one
SELECT id, user_id, series_id, current_season, current_episode, status, created_at, updated_at
FROM user_progress
WHERE user_id = $1 AND series_id = $2
`

type GetUserProgressParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	SeriesID pgtype.UUID `json:"series_id"`
}

func (q *Queries) GetUserProgress(ctx context.Context, arg GetUserProgressParams) (UserProgress, error) {
	row := q.db.QueryRow(ctx, getUserProgress, arg.UserID, arg.SeriesID)
	var i UserProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesID,
		&i.CurrentSeason,
		&i.CurrentEpisode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProgressList = `-- name: GetUserProgressList :many
SELECT up.id, up.user_id, up.series_id, up.current_season, up.current_episode, up.status, up.created_at, up.updated_at,
       s.id as s_id, s.kinopoisk_id, s.title, s.original_title, s.poster_url, s.year, s.description, s.total_episodes, s.total_seasons, s.is_serial
FROM user_progress up
JOIN series s ON up.series_id = s.id
WHERE up.user_id = $1 AND up.status = $2
ORDER BY up.updated_at DESC
`

type GetUserProgressListParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
}

type GetUserProgressListRow struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	SeriesID       pgtype.UUID      `json:"series_id"`
	CurrentSeason  int32            `json:"current_season"`
	CurrentEpisode int32            `json:"current_episode"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	SID            pgtype.UUID      `json:"s_id"`
	KinopoiskID    int32            `json:"kinopoisk_id"`
	Title          string           `json:"title"`
	OriginalTitle  pgtype.Text      `json:"original_title"`
	PosterUrl      pgtype.Text      `json:"poster_url"`
	Year           pgtype.Int4      `json:"year"`
	Description    pgtype.Text      `json:"description"`
	TotalEpisodes  pgtype.Int4      `json:"total_episodes"`
	TotalSeasons   pgtype.Int4      `json:"total_seasons"`
	IsSerial       pgtype.Bool      `json:"is_serial"`
}

func (q *Queries) GetUserProgressList(ctx context.Context, arg GetUserProgressListParams) ([]GetUserProgressListRow, error) {
	rows, err := q.db.Query(ctx, getUserProgressList, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserProgressListRow{}
	for rows.Next() {
		var i GetUserProgressListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeriesID,
			&i.CurrentSeason,
			&i.CurrentEpisode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.KinopoiskID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterUrl,
			&i.Year,
			&i.Description,
			&i.TotalEpisodes,
			&i.TotalSeasons,
			&i.IsSerial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProgress = `-- name: UpdateUserProgress :one
UPDATE user_progress
SET current_season = $3, current_episode = $4, status = $5, updated_at = NOW()
WHERE user_id = $1 AND series_id = $2
RETURNING id, user_id, series_id, current_season, current_episode, status, created_at, updated_at
`

type UpdateUserProgressParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	SeriesID       pgtype.UUID `json:"series_id"`
	CurrentSeason  int32       `json:"current_season"`
	CurrentEpisode int32       `json:"current_episode"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdateUserProgress(ctx context.Context, arg UpdateUserProgressParams) (UserProgress, error) {
	row := q.db.QueryRow(ctx, updateUserProgress,
		arg.UserID,
		arg.SeriesID,
		arg.CurrentSeason,
		arg.CurrentEpisode,
		arg.Status,
	)
	var i UserProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesID,
		&i.CurrentSeason,
		&i.CurrentEpisode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
